ansible_connection : network_cli
ansible_network_os : ios
ansible_python_interpreter : /usr/bin/python3
host_key_checking : False
ansible_ssh_user : developer
ansible_ssh_pass : C1sco12345
ansible_port: 22

commands:
  - "show version"
  - "show ip interface brief"