---
- name: Show examples
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: GATHERING FACTS
    ios_facts:
      gather_subset: hardware

  - name: run show vty configuration
    ios_command:
      commands: sh run | i vty
    register: vty_configuration
  
  - name: display vty configuration
    debug:
      var: vty_configuration["stdout_lines"][0]