---
- name: Show examples
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: GATHERING FACTS
    ios_facts:
      gather_subset: hardware

  - name: run show ntp configuration
    ios_command:
      commands: sh run | i ntp
    register: ntp_configuration
  
  - name: display ntp configuration
    debug:
      var: ntp_configuration["stdout_lines"][0]