---
- name: Show examples
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: GATHERING FACTS
    ios_facts:
      gather_subset: hardware

  - name: run show interface stats
    ios_command:
      commands: show interface stats
    register: interface_stats
  
  - name: display interface stats
    debug:
      var: interface_stats["stdout_lines"][0]