---
- name: Show examples
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: GATHERING FACTS
    ios_facts:
      gather_subset: hardware

  - name: run show aaa configuration
    ios_command:
      commands: sh run | i aaa
    register: aaa_configuration
  
  - name: display aaa configuration
    debug:
      var: aaa_configuration["stdout_lines"][0]