---
- name: Show examples
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: GATHERING FACTS
    ios_facts:
      gather_subset: hardware

  - name: run show version
    ios_command:
      commands: show version
    register: version
  
  - name: display version
    debug:
      var: version["stdout_lines"][0]